### ISSUE TITLE
Nuxt 3:  Error in $fetchraw2 @ ohmyfetch after npm run dev

### ISSUE THREAD

**Issue by sh0ber** [nuxt-modules/google-fonts#123]
OS:  Windows 11
nuxt:  3.2.2
@nuxtjs/google-fonts:  3.0.0-1

I'm using nuxt@3.2.2 + @nuxtjs/google-fonts@3.0.0-1 on a new PC (Windows 11) and I'm getting the following error when running `npm run dev` on brand new Nuxt projects, with nothing else installed except @nuxtjs/google-fonts:

> ERROR  fetch failed ()   
  at async Function.$fetchRaw2 [as raw] (/D:/mysite/node_modules/ohmyfetch/dist/shared/ohmyfetch.d1948a88.mjs:144:20)
  at async /D:/mysite/node_modules/google-fonts-helper/dist/index.mjs:184:24
  at async Promise.all (index 0)
  at async Downloader.execute (/D:/mysite/node_modules/google-fonts-helper/dist/index.mjs:174:20)
  at async setup (/D:/mysite/node_modules/@nuxtjs/google-fonts/dist/module.mjs:70:9)
  at async normalizedModule (/D:/mysite/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (/D:/mysite/node_modules/@nuxt/kit/dist/index.mjs:435:15)
  at async initNuxt (/D:/mysite/node_modules/nuxt/dist/index.mjs:2253:7)
  at async load (/D:/mysite/node_modules/nuxi/dist/chunks/dev.mjs:6802:9)
  at async Object.invoke (/D:/mysite/node_modules/nuxi/dist/chunks/dev.mjs:6863:5)

The project then loads on the dev server but with no Google fonts.  My nuxt.config.ts is simple:

```
export default defineNuxtConfig({
  modules: [
    '@nuxtjs/google-fonts'
  ],
  googleFonts: {
    families: {
      Inter: [400, 700],
      Montserrat: [700]
    }
  }
})
```

The error occurs in google-fonts-helper, which uses ohmyfetch to download fonts for self-hosting.  (For that reason, disabling font download via `download: false` in the nuxt.config.ts `googleFonts` option removes this error, but then there's no font download.)

Someone on a seemingly related thread (https://github.com/unjs/ofetch/issues/156#issuecomment-1294522000) suggested modifying the `dev` entry in package.json as follows, but this did not help me:
```
nuxt dev --host 127.0.0.1
```

Any ideas?

**Comment by sh0ber** [comment]
The only solution that worked for me so far was downgrading to Node 16:
https://nodejs.org/dist/latest-v16.x/
